"""
Employee model - HR profile and organizational data.

Separate from user_model.py to maintain clean separation:
- user_model.py = Authentication, login, roles
- employee_model.py = HR profile, department, designation, reporting, leaves, claims

Pattern:
- One user can have one employee profile via user_id
- Employee references master data collections
- Leave balances are initialized from leave_types
- Claim limits are initialized from claim_types
- Soft delete is handled using is_active and employment_status

Important:
- Employee code is unique and usually auto-generated by service layer
- Manager validation and circular reference checks should be handled in service layer
- Department/designation existence validation should be handled in service layer
- Leave/claim balances are dynamic and tracked per year
- Sensitive data should be returned only to authorized users
"""

from __future__ import annotations

import re
from datetime import date, datetime
from enum import Enum
from typing import List, Optional

from pydantic import (
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    field_validator,
    model_validator,
)


# -------------------------
# Enums
# -------------------------


class EmploymentStatus(str, Enum):
    """Current employment lifecycle status."""

    ACTIVE = "active"
    PROBATION = "probation"
    NOTICE_PERIOD = "notice_period"
    RESIGNED = "resigned"
    TERMINATED = "terminated"
    ABSCONDED = "absconded"
    RETIRED = "retired"
    ON_HOLD = "on_hold"


class EmployeeType(str, Enum):
    """Employment type."""

    FULL_TIME = "full_time"
    PART_TIME = "part_time"
    CONTRACT = "contract"
    INTERN = "intern"
    CONSULTANT = "consultant"


class WorkMode(str, Enum):
    """Employee work mode."""

    OFFICE = "office"
    REMOTE = "remote"
    HYBRID = "hybrid"


class MaritalStatus(str, Enum):
    """Marital status."""

    SINGLE = "single"
    MARRIED = "married"
    DIVORCED = "divorced"
    WIDOWED = "widowed"


class Gender(str, Enum):
    """Gender.

    Keep this optional in employee profile to avoid forcing employees to disclose.
    """

    MALE = "male"
    FEMALE = "female"
    OTHER = "other"
    PREFER_NOT_TO_SAY = "prefer_not_to_say"


class BloodGroup(str, Enum):
    """Blood group."""

    A_POSITIVE = "A+"
    A_NEGATIVE = "A-"
    B_POSITIVE = "B+"
    B_NEGATIVE = "B-"
    O_POSITIVE = "O+"
    O_NEGATIVE = "O-"
    AB_POSITIVE = "AB+"
    AB_NEGATIVE = "AB-"


# -------------------------
# Shared helpers
# -------------------------


PHONE_PATTERN = re.compile(r"^\+?[0-9][0-9\s\-]{8,18}[0-9]$")
PAN_PATTERN = re.compile(r"^[A-Z]{5}[0-9]{4}[A-Z]$")
IFSC_PATTERN = re.compile(r"^[A-Z]{4}0[A-Z0-9]{6}$")
AADHAAR_PATTERN = re.compile(r"^[0-9]{12}$")
PINCODE_PATTERN = re.compile(r"^[0-9A-Za-z][0-9A-Za-z\s\-]{2,18}[0-9A-Za-z]$")


def normalize_optional_text(value: Optional[str]) -> Optional[str]:
    """
    Strip optional text fields.

    Empty strings become None.
    """
    if value is None:
        return None

    value = str(value).strip()
    return value or None


def normalize_phone(value: Optional[str]) -> Optional[str]:
    """
    Normalize and validate phone number.

    Allows:
    - digits
    - +
    - spaces
    - hyphen
    """
    value = normalize_optional_text(value)

    if value is None:
        return None

    if not PHONE_PATTERN.match(value):
        raise ValueError("Invalid phone number format")

    return value


def normalize_pincode(value: Optional[str]) -> Optional[str]:
    """
    Normalize and validate postal/pincode value.
    """
    value = normalize_optional_text(value)

    if value is None:
        return None

    if not PINCODE_PATTERN.match(value):
        raise ValueError("Invalid pincode/postal code format")

    return value


def mask_value(value: Optional[str], visible_last: int = 4) -> Optional[str]:
    """
    Mask sensitive values for safe responses.

    Example:
    123456789012 -> ********9012
    """
    if not value:
        return None

    value = str(value)

    if len(value) <= visible_last:
        return "*" * len(value)

    return "*" * (len(value) - visible_last) + value[-visible_last:]


# -------------------------
# Nested Models
# -------------------------


class Address(BaseModel):
    """Address information."""

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    line1: str = Field(
        ...,
        min_length=2,
        max_length=200,
        description="Address line 1",
    )

    line2: Optional[str] = Field(
        default=None,
        max_length=200,
        description="Address line 2",
    )

    city: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="City",
    )

    state: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="State",
    )

    pincode: str = Field(
        ...,
        min_length=3,
        max_length=20,
        description="Pincode or postal code",
    )

    country: str = Field(
        default="India",
        min_length=2,
        max_length=100,
        description="Country",
    )

    @field_validator("line2")
    @classmethod
    def clean_line2(cls, value: Optional[str]) -> Optional[str]:
        return normalize_optional_text(value)

    @field_validator("pincode")
    @classmethod
    def validate_pincode(cls, value: str) -> str:
        normalized = normalize_pincode(value)
        if normalized is None:
            raise ValueError("pincode is required")
        return normalized


class LeaveBalance(BaseModel):
    """Leave balance for a specific leave type and year."""

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    leave_type_id: str = Field(..., description="Reference to leave_types._id")
    leave_type_code: str = Field(..., min_length=2, max_length=30)
    leave_type_name: str = Field(..., min_length=2, max_length=100)

    granted: float = Field(default=0.0, ge=0.0, description="Granted leave days")
    used: float = Field(default=0.0, ge=0.0, description="Used leave days")
    available: float = Field(default=0.0, ge=0.0, description="Available leave days")
    carried_forward: float = Field(default=0.0, ge=0.0)
    encashed: float = Field(default=0.0, ge=0.0)

    year: int = Field(..., ge=2000, le=2100, description="Leave year")

    @field_validator("leave_type_code")
    @classmethod
    def normalize_leave_type_code(cls, value: str) -> str:
        value = value.strip().upper()
        if not value.replace("_", "").replace("-", "").isalnum():
            raise ValueError("leave_type_code can contain only letters, numbers, hyphen, and underscore")
        return value

    @model_validator(mode="after")
    def validate_leave_balance(self):
        """
        Validate leave balance consistency.

        Formula:
        available should not exceed granted + carried_forward.
        used + encashed should not exceed granted + carried_forward unless
        negative balance is explicitly allowed later by leave service.
        """
        total_entitled = self.granted + self.carried_forward

        if self.available > total_entitled:
            raise ValueError("available leave cannot exceed granted + carried_forward")

        if self.used + self.encashed > total_entitled:
            raise ValueError("used + encashed cannot exceed granted + carried_forward")

        return self


class ClaimLimit(BaseModel):
    """Claim limit for a specific claim type and year."""

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    claim_type_id: str = Field(..., description="Reference to claim_types._id")
    claim_type_code: str = Field(..., min_length=2, max_length=30)
    claim_type_name: str = Field(..., min_length=2, max_length=100)

    annual_limit: float = Field(default=0.0, ge=0.0)
    monthly_limit: Optional[float] = Field(default=None, ge=0.0)

    used: float = Field(default=0.0, ge=0.0)
    available: float = Field(default=0.0, ge=0.0)

    year: int = Field(..., ge=2000, le=2100)

    @field_validator("claim_type_code")
    @classmethod
    def normalize_claim_type_code(cls, value: str) -> str:
        value = value.strip().upper()
        if not value.replace("_", "").replace("-", "").isalnum():
            raise ValueError("claim_type_code can contain only letters, numbers, hyphen, and underscore")
        return value

    @model_validator(mode="after")
    def validate_claim_limit(self):
        if self.monthly_limit is not None and self.monthly_limit > self.annual_limit:
            raise ValueError("monthly_limit cannot be greater than annual_limit")

        if self.used > self.annual_limit:
            raise ValueError("used claim amount cannot exceed annual_limit")

        if self.available > self.annual_limit:
            raise ValueError("available claim amount cannot exceed annual_limit")

        return self


class EmergencyContact(BaseModel):
    """Emergency contact information."""

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    name: str = Field(..., min_length=2, max_length=100)
    relationship: str = Field(..., min_length=2, max_length=50)
    phone: str = Field(..., min_length=10, max_length=20)
    alternate_phone: Optional[str] = Field(default=None, max_length=20)

    @field_validator("name")
    @classmethod
    def normalize_name(cls, value: str) -> str:
        return value.strip().title()

    @field_validator("phone")
    @classmethod
    def validate_phone(cls, value: str) -> str:
        normalized = normalize_phone(value)
        if normalized is None:
            raise ValueError("phone is required")
        return normalized

    @field_validator("alternate_phone")
    @classmethod
    def validate_alternate_phone(cls, value: Optional[str]) -> Optional[str]:
        return normalize_phone(value)


class BankDetails(BaseModel):
    """Bank account details for salary payment."""

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    account_holder_name: str = Field(..., min_length=2, max_length=200)
    account_number: str = Field(..., min_length=5, max_length=50)
    bank_name: str = Field(..., min_length=2, max_length=200)
    branch_name: str = Field(..., min_length=2, max_length=200)
    ifsc_code: str = Field(..., min_length=11, max_length=11)

    @field_validator("account_holder_name")
    @classmethod
    def normalize_account_holder_name(cls, value: str) -> str:
        return value.strip().title()

    @field_validator("account_number")
    @classmethod
    def validate_account_number(cls, value: str) -> str:
        value = value.strip().replace(" ", "")

        if not value.isdigit():
            raise ValueError("account_number must contain only digits")

        if len(value) < 5 or len(value) > 50:
            raise ValueError("account_number must be between 5 and 50 digits")

        return value

    @field_validator("ifsc_code")
    @classmethod
    def validate_ifsc(cls, value: str) -> str:
        value = value.strip().upper()

        if not IFSC_PATTERN.match(value):
            raise ValueError("Invalid IFSC code format")

        return value


# -------------------------
# Main Employee Model
# -------------------------


class Employee(BaseModel):
    """
    Employee document model for employees collection.

    Represents HR profile and organizational data.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    # -------------------------
    # Multi-company Support
    # -------------------------

    company_id: str = Field(
        default="default",
        min_length=2,
        max_length=100,
        description="Company identifier for future multi-tenant support",
    )

    # -------------------------
    # Core Identity
    # -------------------------

    employee_code: str = Field(
        ...,
        min_length=3,
        max_length=30,
        description="Unique employee code, usually auto-generated by service layer",
    )

    user_id: str = Field(
        ...,
        description="Reference to users._id for authentication",
    )

    # -------------------------
    # Personal Information
    # -------------------------

    first_name: str = Field(..., min_length=2, max_length=100)
    middle_name: Optional[str] = Field(default=None, max_length=100)
    last_name: str = Field(..., min_length=2, max_length=100)

    email: EmailStr = Field(..., description="Official company email")
    personal_email: Optional[EmailStr] = Field(default=None)

    phone: str = Field(..., min_length=10, max_length=20)
    alternate_phone: Optional[str] = Field(default=None, max_length=20)

    date_of_birth: Optional[date] = Field(default=None)

    gender: Optional[Gender] = Field(default=None)
    marital_status: Optional[MaritalStatus] = Field(default=None)
    blood_group: Optional[BloodGroup] = Field(default=None)

    # -------------------------
    # Organizational Data
    # -------------------------

    department_id: str = Field(..., description="Reference to departments._id")
    designation_id: str = Field(..., description="Reference to designations._id")

    manager_id: Optional[str] = Field(
        default=None,
        description="Reference to employees.employee_code or employees._id depending on service design",
    )

    work_location: str = Field(..., min_length=2, max_length=100)
    work_mode: WorkMode = Field(default=WorkMode.OFFICE)

    # -------------------------
    # Employment Details
    # -------------------------

    joining_date: date = Field(...)

    confirmation_date: Optional[date] = Field(default=None)
    probation_end_date: Optional[date] = Field(default=None)
    resignation_date: Optional[date] = Field(default=None)
    last_working_date: Optional[date] = Field(default=None)

    notice_period_days: int = Field(default=30, ge=0, le=365)

    employment_status: EmploymentStatus = Field(default=EmploymentStatus.PROBATION)
    employee_type: EmployeeType = Field(default=EmployeeType.FULL_TIME)

    # -------------------------
    # Leave Management
    # -------------------------

    leave_balances: List[LeaveBalance] = Field(default_factory=list)

    # -------------------------
    # Claim Management
    # -------------------------

    claim_limits: List[ClaimLimit] = Field(default_factory=list)

    # -------------------------
    # Documents and IDs
    # -------------------------

    pan_number: Optional[str] = Field(default=None, max_length=10)
    aadhaar_number: Optional[str] = Field(default=None, max_length=12)
    passport_number: Optional[str] = Field(default=None, max_length=20)
    driving_license: Optional[str] = Field(default=None, max_length=20)

    # -------------------------
    # Address
    # -------------------------

    current_address: Optional[Address] = Field(default=None)
    permanent_address: Optional[Address] = Field(default=None)

    # -------------------------
    # Emergency Contact
    # -------------------------

    emergency_contact: Optional[EmergencyContact] = Field(default=None)

    # -------------------------
    # Bank Details
    # -------------------------

    bank_details: Optional[BankDetails] = Field(default=None)

    # -------------------------
    # Flags and Metadata
    # -------------------------

    is_active: bool = Field(default=True)

    created_by: Optional[str] = Field(default=None)
    updated_by: Optional[str] = Field(default=None)

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # -------------------------
    # Helper properties
    # -------------------------

    @property
    def full_name(self) -> str:
        """
        Return computed full name.

        Not stored directly in MongoDB.
        Service/response layer can use this for display.
        """
        parts = [self.first_name, self.middle_name, self.last_name]
        return " ".join(part for part in parts if part)

    # -------------------------
    # Validators
    # -------------------------

    @field_validator("company_id")
    @classmethod
    def validate_company_id(cls, value: str) -> str:
        value = value.strip().lower()

        if not value:
            raise ValueError("company_id cannot be empty")

        if not value.replace("_", "").replace("-", "").isalnum():
            raise ValueError("company_id can contain only letters, numbers, hyphen, and underscore")

        return value

    @field_validator("employee_code")
    @classmethod
    def validate_employee_code(cls, value: str) -> str:
        value = value.strip().upper()

        if not value.replace("_", "").replace("-", "").isalnum():
            raise ValueError("employee_code can contain only letters, numbers, hyphen, and underscore")

        return value

    @field_validator("first_name", "last_name")
    @classmethod
    def validate_required_name(cls, value: str) -> str:
        value = value.strip()

        if not value:
            raise ValueError("name cannot be empty")

        if any(char.isdigit() for char in value):
            raise ValueError("name cannot contain numbers")

        return value.title()

    @field_validator("middle_name")
    @classmethod
    def validate_optional_name(cls, value: Optional[str]) -> Optional[str]:
        value = normalize_optional_text(value)

        if value is None:
            return None

        if any(char.isdigit() for char in value):
            raise ValueError("middle_name cannot contain numbers")

        return value.title()

    @field_validator("phone")
    @classmethod
    def validate_phone(cls, value: str) -> str:
        normalized = normalize_phone(value)
        if normalized is None:
            raise ValueError("phone is required")
        return normalized

    @field_validator("alternate_phone")
    @classmethod
    def validate_alternate_phone(cls, value: Optional[str]) -> Optional[str]:
        return normalize_phone(value)

    @field_validator("work_location")
    @classmethod
    def normalize_work_location(cls, value: str) -> str:
        return value.strip().title()

    @field_validator("manager_id", "created_by", "updated_by")
    @classmethod
    def normalize_optional_ids(cls, value: Optional[str]) -> Optional[str]:
        return normalize_optional_text(value)

    @field_validator("pan_number")
    @classmethod
    def validate_pan(cls, value: Optional[str]) -> Optional[str]:
        value = normalize_optional_text(value)

        if value is None:
            return None

        value = value.upper()

        if not PAN_PATTERN.match(value):
            raise ValueError("Invalid PAN number format")

        return value

    @field_validator("aadhaar_number")
    @classmethod
    def validate_aadhaar(cls, value: Optional[str]) -> Optional[str]:
        value = normalize_optional_text(value)

        if value is None:
            return None

        value = value.replace(" ", "")

        if not AADHAAR_PATTERN.match(value):
            raise ValueError("Aadhaar must be exactly 12 digits")

        return value

    @field_validator("passport_number", "driving_license")
    @classmethod
    def normalize_document_ids(cls, value: Optional[str]) -> Optional[str]:
        value = normalize_optional_text(value)

        if value is None:
            return None

        return value.upper()

    @model_validator(mode="after")
    def validate_dates_and_status(self):
        """
        Validate employment date consistency.
        """
        today = date.today()

        if self.date_of_birth is not None:
            if self.date_of_birth >= today:
                raise ValueError("date_of_birth must be in the past")

            minimum_age_years = 14
            age = (
                today.year
                - self.date_of_birth.year
                - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
            )

            if age < minimum_age_years:
                raise ValueError("Employee age must be at least 14 years")

        if self.probation_end_date and self.probation_end_date < self.joining_date:
            raise ValueError("probation_end_date cannot be before joining_date")

        if self.confirmation_date and self.confirmation_date < self.joining_date:
            raise ValueError("confirmation_date cannot be before joining_date")

        if self.resignation_date and self.resignation_date < self.joining_date:
            raise ValueError("resignation_date cannot be before joining_date")

        if self.last_working_date and self.last_working_date < self.joining_date:
            raise ValueError("last_working_date cannot be before joining_date")

        if self.resignation_date and self.last_working_date:
            if self.last_working_date < self.resignation_date:
                raise ValueError("last_working_date cannot be before resignation_date")

        if self.employment_status == EmploymentStatus.ACTIVE:
            if not self.is_active:
                raise ValueError("ACTIVE employee must have is_active=True")

        if self.employment_status in {
            EmploymentStatus.RESIGNED,
            EmploymentStatus.TERMINATED,
            EmploymentStatus.ABSCONDED,
            EmploymentStatus.RETIRED,
        }:
            if self.is_active:
                raise ValueError("Exited employees should have is_active=False")

        if self.employment_status == EmploymentStatus.NOTICE_PERIOD:
            if not self.resignation_date:
                raise ValueError("resignation_date is required for notice_period status")

        return self


class EmployeeInDB(Employee):
    """Employee model as stored in MongoDB with _id field."""

    id: Optional[str] = Field(default=None, alias="_id")

    model_config = ConfigDict(
        populate_by_name=True,
        str_strip_whitespace=True,
        validate_assignment=True,
    )


# -------------------------
# Response Models
# -------------------------


class EmployeeResponse(BaseModel):
    """
    Safe employee response for normal API output.

    This response intentionally masks sensitive fields.
    For full private HR/admin details, use EmployeePrivateResponse.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str
    company_id: str

    employee_code: str
    user_id: str

    # Personal
    first_name: str
    middle_name: Optional[str] = None
    last_name: str
    full_name: str

    email: EmailStr
    personal_email: Optional[EmailStr] = None

    phone: str
    alternate_phone: Optional[str] = None

    date_of_birth: Optional[date] = None
    gender: Optional[Gender] = None
    marital_status: Optional[MaritalStatus] = None
    blood_group: Optional[BloodGroup] = None

    # Organizational
    department_id: str
    department_name: Optional[str] = None

    designation_id: str
    designation_name: Optional[str] = None

    manager_id: Optional[str] = None
    manager_name: Optional[str] = None

    work_location: str
    work_mode: WorkMode

    # Employment
    joining_date: date
    confirmation_date: Optional[date] = None
    probation_end_date: Optional[date] = None
    resignation_date: Optional[date] = None
    last_working_date: Optional[date] = None

    notice_period_days: int
    employment_status: EmploymentStatus
    employee_type: EmployeeType

    # Leave and Claims
    leave_balances: List[LeaveBalance] = Field(default_factory=list)
    claim_limits: List[ClaimLimit] = Field(default_factory=list)

    # Documents - masked in normal response
    pan_number: Optional[str] = None
    aadhaar_number: Optional[str] = None

    # Address
    current_address: Optional[Address] = None
    permanent_address: Optional[Address] = None

    # Emergency
    emergency_contact: Optional[EmergencyContact] = None

    # Bank - avoid exposing full bank details in normal response
    bank_details_available: bool = False

    # Metadata
    is_active: bool
    created_at: datetime
    updated_at: datetime


class EmployeePrivateResponse(EmployeeResponse):
    """
    Private employee response for HR/Admin only.

    Includes sensitive document and bank details.
    Use only in protected endpoints.
    """

    passport_number: Optional[str] = None
    driving_license: Optional[str] = None
    bank_details: Optional[BankDetails] = None

    created_by: Optional[str] = None
    updated_by: Optional[str] = None


class EmployeeSummary(BaseModel):
    """Lightweight employee summary for lists."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    company_id: str
    employee_code: str
    full_name: str
    email: EmailStr
    phone: str

    department_id: Optional[str] = None
    department_name: Optional[str] = None

    designation_id: Optional[str] = None
    designation_name: Optional[str] = None

    manager_id: Optional[str] = None
    manager_name: Optional[str] = None

    work_location: Optional[str] = None
    work_mode: Optional[WorkMode] = None

    employment_status: EmploymentStatus
    employee_type: EmployeeType
    is_active: bool


class EmployeeDropdown(BaseModel):
    """Employee dropdown option for UI selects."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    employee_code: str
    full_name: str

    designation_name: Optional[str] = None
    department_name: Optional[str] = None

    employment_status: EmploymentStatus
    is_active: bool


class EmployeeManagerOption(BaseModel):
    """
    Manager dropdown option.

    Useful when selecting reporting manager.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str
    employee_code: str
    full_name: str
    email: EmailStr

    designation_name: Optional[str] = None
    department_name: Optional[str] = None