"""
Employee schemas - Request/Response models for Employee API endpoints.

This file contains Pydantic schemas for:
- Creating employees
- Updating employee profiles
- Updating employment status
- Employee responses with enriched data
- Employee filters and search
- Dropdown options
- Statistics responses

Pattern:
- Request schemas validate API input
- Response schemas define safe API output
- Model file defines MongoDB document structure
- Repository handles MongoDB operations only
- Service handles business validation
"""

from __future__ import annotations

from datetime import date, datetime
from typing import List, Literal, Optional

from pydantic import (
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    field_validator,
    model_validator,
)

from backend.app.models.employee_model import (
    Address,
    BankDetails,
    BloodGroup,
    ClaimLimit,
    EmergencyContact,
    EmployeeType,
    EmploymentStatus,
    Gender,
    LeaveBalance,
    MaritalStatus,
    WorkMode,
)


# -------------------------
# Shared helpers
# -------------------------


def normalize_optional_text(value: Optional[str]) -> Optional[str]:
    """
    Strip optional text fields.

    Empty string becomes None.
    """
    if value is None:
        return None

    value = str(value).strip()
    return value or None


def normalize_company_id(value: Optional[str]) -> str:
    """
    Normalize company_id.

    Rules:
    - default if missing
    - lowercase
    - only letters, numbers, hyphen, underscore
    """
    if value is None:
        return "default"

    value = str(value).strip().lower()

    if not value:
        return "default"

    if not value.replace("_", "").replace("-", "").isalnum():
        raise ValueError(
            "company_id can contain only letters, numbers, hyphen, and underscore"
        )

    return value


# -------------------------
# Request Schemas
# -------------------------


class CreateEmployeeRequest(BaseModel):
    """
    Request schema for creating a new employee.

    Employee code is normally generated by service/repository.
    Do not ask frontend to send employee_code unless you want manual override later.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        extra="forbid",
    )

    # Multi-company
    company_id: str = Field(
        default="default",
        min_length=2,
        max_length=100,
        description="Company identifier",
    )

    # Core identity
    user_id: str = Field(
        ...,
        description="Reference to users._id",
    )

    # Personal information
    first_name: str = Field(..., min_length=2, max_length=100)
    middle_name: Optional[str] = Field(default=None, max_length=100)
    last_name: str = Field(..., min_length=2, max_length=100)

    email: EmailStr = Field(..., description="Official company email")
    personal_email: Optional[EmailStr] = None

    phone: str = Field(..., min_length=10, max_length=20)
    alternate_phone: Optional[str] = Field(default=None, max_length=20)

    date_of_birth: Optional[date] = None

    gender: Optional[Gender] = None
    marital_status: Optional[MaritalStatus] = None
    blood_group: Optional[BloodGroup] = None

    # Organizational data
    department_id: str = Field(..., description="Reference to departments._id")
    designation_id: str = Field(..., description="Reference to designations._id")

    manager_id: Optional[str] = Field(
        default=None,
        description="Reference to reporting manager employee id/code depending on service design",
    )

    work_location: str = Field(..., min_length=2, max_length=100)
    work_mode: WorkMode = Field(default=WorkMode.OFFICE)

    # Employment details
    joining_date: date = Field(..., description="Date of joining")
    probation_end_date: Optional[date] = None

    notice_period_days: int = Field(default=30, ge=0, le=365)

    employment_status: EmploymentStatus = Field(default=EmploymentStatus.PROBATION)
    employee_type: EmployeeType = Field(default=EmployeeType.FULL_TIME)

    # Documents
    pan_number: Optional[str] = Field(default=None, max_length=10)
    aadhaar_number: Optional[str] = Field(default=None, max_length=12)
    passport_number: Optional[str] = Field(default=None, max_length=20)
    driving_license: Optional[str] = Field(default=None, max_length=20)

    # Address
    current_address: Optional[Address] = None
    permanent_address: Optional[Address] = None

    # Emergency contact
    emergency_contact: Optional[EmergencyContact] = None

    # Bank details
    bank_details: Optional[BankDetails] = None

    @field_validator("company_id")
    @classmethod
    def validate_company_id(cls, value: str) -> str:
        return normalize_company_id(value)

    @field_validator("middle_name", "manager_id", "passport_number", "driving_license")
    @classmethod
    def clean_optional_text_fields(cls, value: Optional[str]) -> Optional[str]:
        return normalize_optional_text(value)

    @model_validator(mode="after")
    def validate_create_dates(self):
        """
        Basic create-time date validation.

        Deeper validation remains in Employee model/service.
        """
        if self.probation_end_date and self.probation_end_date < self.joining_date:
            raise ValueError("probation_end_date cannot be before joining_date")

        return self


class UpdateEmployeeRequest(BaseModel):
    """
    Request schema for updating employee profile.

    Only provided fields are updated.
    Service should use exclude_unset=True.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        extra="forbid",
    )

    # Personal information
    first_name: Optional[str] = Field(default=None, min_length=2, max_length=100)
    middle_name: Optional[str] = Field(default=None, max_length=100)
    last_name: Optional[str] = Field(default=None, min_length=2, max_length=100)

    personal_email: Optional[EmailStr] = None

    phone: Optional[str] = Field(default=None, min_length=10, max_length=20)
    alternate_phone: Optional[str] = Field(default=None, max_length=20)

    date_of_birth: Optional[date] = None

    gender: Optional[Gender] = None
    marital_status: Optional[MaritalStatus] = None
    blood_group: Optional[BloodGroup] = None

    # Organizational data
    department_id: Optional[str] = None
    designation_id: Optional[str] = None
    manager_id: Optional[str] = None

    work_location: Optional[str] = Field(default=None, min_length=2, max_length=100)
    work_mode: Optional[WorkMode] = None

    # Employment details
    confirmation_date: Optional[date] = None
    probation_end_date: Optional[date] = None
    resignation_date: Optional[date] = None
    last_working_date: Optional[date] = None

    notice_period_days: Optional[int] = Field(default=None, ge=0, le=365)

    employment_status: Optional[EmploymentStatus] = None
    employee_type: Optional[EmployeeType] = None

    # Documents
    pan_number: Optional[str] = Field(default=None, max_length=10)
    aadhaar_number: Optional[str] = Field(default=None, max_length=12)
    passport_number: Optional[str] = Field(default=None, max_length=20)
    driving_license: Optional[str] = Field(default=None, max_length=20)

    # Address
    current_address: Optional[Address] = None
    permanent_address: Optional[Address] = None

    # Emergency contact
    emergency_contact: Optional[EmergencyContact] = None

    # Bank details
    bank_details: Optional[BankDetails] = None

    @field_validator("middle_name", "manager_id", "passport_number", "driving_license")
    @classmethod
    def clean_optional_text_fields(cls, value: Optional[str]) -> Optional[str]:
        return normalize_optional_text(value)

    @model_validator(mode="after")
    def validate_at_least_one_field(self):
        """
        Prevent empty update payload.
        """
        values = self.model_dump(exclude_unset=True)

        if not values:
            raise ValueError("At least one field must be provided for update")

        return self

    @model_validator(mode="after")
    def validate_update_dates(self):
        """
        Basic update-time date validation when related fields are present together.
        """
        if self.resignation_date and self.last_working_date:
            if self.last_working_date < self.resignation_date:
                raise ValueError("last_working_date cannot be before resignation_date")

        return self


class UpdateEmploymentStatusRequest(BaseModel):
    """
    Request schema for updating employment status.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        extra="forbid",
    )

    employment_status: EmploymentStatus = Field(
        ...,
        description="New employment status",
    )

    effective_date: Optional[date] = Field(
        default=None,
        description="Effective date of status change",
    )

    resignation_date: Optional[date] = Field(
        default=None,
        description="Required when moving to notice_period/resigned in service logic",
    )

    last_working_date: Optional[date] = Field(
        default=None,
        description="Last working date for resigned/terminated/retired employees",
    )

    confirmation_date: Optional[date] = Field(
        default=None,
        description="Confirmation date when changing from probation to active",
    )

    remarks: Optional[str] = Field(
        default=None,
        max_length=500,
        description="Remarks for status change",
    )

    @field_validator("remarks")
    @classmethod
    def clean_remarks(cls, value: Optional[str]) -> Optional[str]:
        return normalize_optional_text(value)

    @model_validator(mode="after")
    def validate_status_dates(self):
        if self.resignation_date and self.last_working_date:
            if self.last_working_date < self.resignation_date:
                raise ValueError("last_working_date cannot be before resignation_date")

        return self


class UpdateManagerRequest(BaseModel):
    """
    Request schema for updating reporting manager.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        extra="forbid",
    )

    manager_id: Optional[str] = Field(
        default=None,
        description="New manager id/code. Use null to remove manager.",
    )

    @field_validator("manager_id")
    @classmethod
    def clean_manager_id(cls, value: Optional[str]) -> Optional[str]:
        return normalize_optional_text(value)


class UpdateBankDetailsRequest(BaseModel):
    """
    Request schema for updating bank details.
    """

    model_config = ConfigDict(extra="forbid")

    bank_details: BankDetails = Field(..., description="Updated bank details")


class UpdateEmergencyContactRequest(BaseModel):
    """
    Request schema for updating emergency contact.
    """

    model_config = ConfigDict(extra="forbid")

    emergency_contact: EmergencyContact = Field(
        ...,
        description="Updated emergency contact",
    )


class UpdateEmployeeAddressRequest(BaseModel):
    """
    Request schema for updating employee addresses.
    """

    model_config = ConfigDict(extra="forbid")

    current_address: Optional[Address] = None
    permanent_address: Optional[Address] = None

    @model_validator(mode="after")
    def validate_at_least_one_address(self):
        if self.current_address is None and self.permanent_address is None:
            raise ValueError("At least one address must be provided")

        return self


class UpdateLeaveBalancesRequest(BaseModel):
    """
    Request schema for replacing employee leave balances.

    Usually used by HR/Admin or leave initialization service.
    """

    model_config = ConfigDict(extra="forbid")

    leave_balances: List[LeaveBalance] = Field(default_factory=list)


class UpdateClaimLimitsRequest(BaseModel):
    """
    Request schema for replacing employee claim limits.

    Usually used by HR/Admin or claim initialization service.
    """

    model_config = ConfigDict(extra="forbid")

    claim_limits: List[ClaimLimit] = Field(default_factory=list)


# -------------------------
# Response Schemas
# -------------------------


class EmployeeResponse(BaseModel):
    """
    Normal employee response with enriched data.

    Use this for normal authenticated users.
    Sensitive bank details should not be exposed here.
    """

    model_config = ConfigDict(from_attributes=True)

    # Core identity
    id: str
    company_id: str
    employee_code: str
    user_id: str

    # Personal information
    first_name: str
    middle_name: Optional[str] = None
    last_name: str
    full_name: str

    email: EmailStr
    personal_email: Optional[EmailStr] = None

    phone: str
    alternate_phone: Optional[str] = None

    date_of_birth: Optional[date] = None

    gender: Optional[Gender] = None
    marital_status: Optional[MaritalStatus] = None
    blood_group: Optional[BloodGroup] = None

    # Organizational data
    department_id: str
    department_name: Optional[str] = None
    department_code: Optional[str] = None

    designation_id: str
    designation_name: Optional[str] = None
    designation_code: Optional[str] = None

    manager_id: Optional[str] = None
    manager_name: Optional[str] = None
    manager_employee_code: Optional[str] = None

    work_location: str
    work_mode: WorkMode

    # Employment details
    joining_date: date
    confirmation_date: Optional[date] = None
    probation_end_date: Optional[date] = None
    resignation_date: Optional[date] = None
    last_working_date: Optional[date] = None

    notice_period_days: int
    employment_status: EmploymentStatus
    employee_type: EmployeeType

    # Leave and claim balances
    leave_balances: List[LeaveBalance] = Field(default_factory=list)
    claim_limits: List[ClaimLimit] = Field(default_factory=list)

    # Documents - safe/masked values should be added by service if needed
    pan_number: Optional[str] = None
    aadhaar_number: Optional[str] = None

    # Address
    current_address: Optional[Address] = None
    permanent_address: Optional[Address] = None

    # Emergency contact
    emergency_contact: Optional[EmergencyContact] = None

    # Bank
    bank_details_available: bool = False

    # Metadata
    is_active: bool
    created_at: datetime
    updated_at: datetime


class EmployeePrivateResponse(EmployeeResponse):
    """
    Private employee response for HR/Admin only.

    Includes sensitive details.
    Use only in protected HR/Admin routes.
    """

    passport_number: Optional[str] = None
    driving_license: Optional[str] = None
    bank_details: Optional[BankDetails] = None

    created_by: Optional[str] = None
    updated_by: Optional[str] = None


class EmployeeSummaryResponse(BaseModel):
    """
    Lightweight employee summary for list pages.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str
    company_id: str

    employee_code: str
    full_name: str

    email: EmailStr
    phone: str

    department_id: Optional[str] = None
    department_name: Optional[str] = None
    department_code: Optional[str] = None

    designation_id: Optional[str] = None
    designation_name: Optional[str] = None
    designation_code: Optional[str] = None

    manager_id: Optional[str] = None
    manager_name: Optional[str] = None

    work_location: Optional[str] = None
    work_mode: Optional[WorkMode] = None

    employment_status: EmploymentStatus
    employee_type: EmployeeType

    joining_date: Optional[date] = None
    is_active: bool


class EmployeeDropdownResponse(BaseModel):
    """
    Employee dropdown option for UI selects.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str
    employee_code: str
    full_name: str

    email: Optional[EmailStr] = None

    designation_name: Optional[str] = None
    department_name: Optional[str] = None

    employment_status: EmploymentStatus
    is_active: bool


class EmployeeManagerOptionResponse(BaseModel):
    """
    Manager dropdown response.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str
    employee_code: str
    full_name: str
    email: EmailStr

    designation_name: Optional[str] = None
    department_name: Optional[str] = None


class EmployeeCreatedResponse(BaseModel):
    """
    Response after successful employee creation.
    """

    message: str = Field(default="Employee created successfully")
    employee_id: str
    employee_code: str
    employee: Optional[EmployeeResponse] = None


class EmployeeUpdatedResponse(BaseModel):
    """
    Response after successful employee update.
    """

    message: str = Field(default="Employee updated successfully")
    employee_code: str
    updated_at: datetime
    employee: Optional[EmployeeResponse] = None


class EmployeeStatusResponse(BaseModel):
    """
    Response after activate/deactivate/status operations.
    """

    message: str
    employee_code: str
    employment_status: EmploymentStatus
    is_active: bool


class EmployeeDeletedResponse(BaseModel):
    """
    Alias-style response for soft delete.

    We do not hard delete employees.
    """

    message: str = Field(default="Employee deactivated successfully")
    employee_code: str
    is_active: bool = False


# -------------------------
# Filter and Search Schemas
# -------------------------


class EmployeeFilterParams(BaseModel):
    """
    Query parameters for filtering employees.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        extra="forbid",
    )

    company_id: str = Field(default="default", min_length=2, max_length=100)

    department_id: Optional[str] = None
    designation_id: Optional[str] = None
    manager_id: Optional[str] = None

    work_location: Optional[str] = None
    work_mode: Optional[WorkMode] = None

    employment_status: Optional[EmploymentStatus] = None
    employee_type: Optional[EmployeeType] = None

    is_active: Optional[bool] = True

    search: Optional[str] = Field(default=None, max_length=100)

    skip: int = Field(default=0, ge=0)
    limit: int = Field(default=100, ge=1, le=500)

    sort_by: Literal[
        "employee_code",
        "first_name",
        "last_name",
        "email",
        "joining_date",
        "created_at",
        "updated_at",
        "employment_status",
        "work_location",
    ] = "employee_code"

    sort_order: Literal["asc", "desc"] = "asc"

    @field_validator("company_id")
    @classmethod
    def validate_company_id(cls, value: str) -> str:
        return normalize_company_id(value)

    @field_validator(
        "department_id",
        "designation_id",
        "manager_id",
        "work_location",
        "search",
    )
    @classmethod
    def clean_optional_filters(cls, value: Optional[str]) -> Optional[str]:
        return normalize_optional_text(value)


class EmployeeSearchParams(BaseModel):
    """
    Query parameters for employee search endpoint.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        extra="forbid",
    )

    company_id: str = Field(default="default", min_length=2, max_length=100)
    query: str = Field(..., min_length=1, max_length=100)

    department_id: Optional[str] = None
    designation_id: Optional[str] = None
    employment_status: Optional[EmploymentStatus] = None

    is_active: Optional[bool] = True

    skip: int = Field(default=0, ge=0)
    limit: int = Field(default=100, ge=1, le=500)

    @field_validator("company_id")
    @classmethod
    def validate_company_id(cls, value: str) -> str:
        return normalize_company_id(value)

    @field_validator("department_id", "designation_id")
    @classmethod
    def clean_optional_filters(cls, value: Optional[str]) -> Optional[str]:
        return normalize_optional_text(value)


# -------------------------
# List Responses
# -------------------------


class EmployeeListResponse(BaseModel):
    """
    Paginated employee list response.
    """

    employees: List[EmployeeSummaryResponse]
    total: int
    skip: int
    limit: int


class EmployeeDropdownListResponse(BaseModel):
    """
    Dropdown employee list response.
    """

    employees: List[EmployeeDropdownResponse]
    total: int


class EmployeeManagerListResponse(BaseModel):
    """
    Manager dropdown/list response.
    """

    managers: List[EmployeeManagerOptionResponse]
    total: int


# -------------------------
# Statistics Responses
# -------------------------


class EmployeeStatisticsResponse(BaseModel):
    """
    Employee statistics response.
    """

    company_id: str = "default"

    total_employees: int
    active_employees: int
    inactive_employees: int

    on_probation: int
    confirmed_employees: int
    notice_period: int

    resigned_employees: int
    terminated_employees: int
    absconded_employees: int = 0
    retired_employees: int = 0


class EmployeeDepartmentStatisticsItem(BaseModel):
    """
    Department-wise employee count item.
    """

    department_id: Optional[str] = None
    department_name: Optional[str] = None
    count: int


class EmployeeDepartmentStatisticsResponse(BaseModel):
    """
    Department-wise employee count response.
    """

    company_id: str = "default"
    departments: List[EmployeeDepartmentStatisticsItem]


class EmployeeStatusStatisticsItem(BaseModel):
    """
    Status-wise employee count item.
    """

    employment_status: str
    count: int


class EmployeeStatusStatisticsResponse(BaseModel):
    """
    Status-wise employee count response.
    """

    company_id: str = "default"
    statuses: List[EmployeeStatusStatisticsItem]


# -------------------------
# Validation / Utility Responses
# -------------------------


class EmployeeExistsResponse(BaseModel):
    """
    Response for employee existence checks.
    """

    exists: bool
    employee_id: Optional[str] = None
    employee_code: Optional[str] = None


class EmployeeValidationResponse(BaseModel):
    """
    Response for validating employee payloads.
    """

    is_valid: bool
    errors: List[dict] = Field(default_factory=list)